name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Run workflow manually

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
              # This special URL extracts the images correctly
              feed_list: "https://medium-rss-v2.vercel.app/feed/@hasupeksha2002" 
              max_post_count: 2
              # This forces the script to look for the image in the right place
              tag_post_image: "image"
              template: "<td><a href='$url'><img width='100%' src='$image' /></a><br/><br/><a href='$url'><b>$title</b></a><br/><i>$date</i></td>"
