name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Run workflow manually

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rsshub.app/medium/profile/hasupeksha2002"
          max_post_count: 2
          template: "<td><a href='$url'><img width='100%' src='$image' /></a><br/><br/><a href='$url'><b>$title</b></a><br/><i>$date</i></td>"
